optimism_package:
  chains:
    - participants:
      - el_type: op-geth
        cl_type: op-node
        node_selectors: {}
        tolerations: []
        count: 1
      network_params:
        network: "kurtosis"
        network_id: "2151908"
        seconds_per_slot: 2
        name: "op-kurtosis"
        fjord_time_offset: 0
        granite_time_offset: 0
        fund_dev_accounts: false
      batcher_params:
        extra_params: []
      challenger_params:
        enabled: true
        extra_params: []
      mev_params:
        builder_host: ""
        builder_port: ""
      additional_services: []
  op_contract_deployer_params:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-deployer:v0.0.12
    l1_artifacts_locator: https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-fffcbb0ebf7f83311791534a41e65ef90df47797f9ca8f86941452f597f7128c.tar.gz
    l2_artifacts_locator: https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-fffcbb0ebf7f83311791534a41e65ef90df47797f9ca8f86941452f597f7128c.tar.gz
  global_log_level: "info"
  global_node_selectors: {}
  global_tolerations: []
  persistent: false
external_l1_network_params:
  network_id: "3151908"
  rpc_kind: standard
  el_rpc_url: http://el-1-geth-lighthouse:8545
  el_ws_url: ws://el-1-geth-lighthouse:8546
  cl_rpc_url: http://cl-1-lighthouse-geth:4000
  priv_key: "0xbcdf20249abf0ed6d944c0288fad489e33f66b3960d9e6229c1cd214ed3bbe31"

